[package]
name = "drg_mission_gen_core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
strum.workspace = true

[dev-dependencies]
serde_json.workspace = true
time.workspace = true
pretty_assertions = "1"
